- name: Ensure the dotfiles folder is created
  file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory
    owner: "{{ ansible_env.USER }}"
    mode: "0755"

- name: Deploy the dotfiles
  hosts: all
  become: no
  roles:
    - role: alacritty
      tags:
        - alacritty

    - role: dunst
      tags:
        - dunst

    - role: hypr
      tags:
        - hypr

    - role: lf
      tags:
        - lf

    - role: qutebrowser
      tags:
        - qutebrowser

    - role: wallpapers
      tags:
        - wallpapers

    - role: waybar
      tags:
        - waybar

    - role: wlogout
      tags:
        - wlogout

    - role: zathura
      tags:
        - zathura
