---
- name: Deploy the zshrc with symlink
  file:
    src: "{{ role_path }}/files/zshrc"
    dest: "{{ ansible_env.HOME }}/.zshrc"
    state: link

- name: Deploy the aliasrc with symlink
  file:
    src: "{{ role_path }}/files/aliasrc"
    dest: "{{ ansible_env.HOME }}/.config/aliasrc"
    state: link
