---
- name: Ensure the zathura config folder is created
  file:
    path: "{{ ansible_env.HOME }}/.config/zathura"
    state: directory
    owner: "{{ ansible_env.USER }}"
    mode: "0755"

- name: Deploy the zathura config with symlink
  file:
    src: "{{ role_path }}/files/zathurarc"
    dest: "{{ ansible_env.HOME }}/.config/zathura/zathurarc"
    state: link
